# Generated by Django 3.0.7 on 2020-07-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='street_address3',
        ),
    ]
